# Generated by Django 3.0 on 2019-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20191227_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=80)),
                ('email', models.CharField(default=' ', max_length=80)),
                ('phone', models.CharField(default=' ', max_length=80)),
                ('desc', models.CharField(default=' ', max_length=5000)),
            ],
        ),
    ]
